version: '3.8'
services:
    server:
        build:
            context: .
        environment:
            NODE_ENV: production
            MONGODB_URI: ${MONGODB_URI}
            JWT_SECRET: ${JWT_SECRET}
            GOOGLE_CAPTCHA_SITE_KEY: ${GOOGLE_CAPTCHA_SITE_KEY}
            GOOGLE_CAPTCHA_SECRET_KEY: ${GOOGLE_CAPTCHA_SECRET_KEY}
            MJ_APIKEY_PUBLIC: ${MJ_APIKEY_PUBLIC}
            MJ_APIKEY_PRIVATE: ${MJ_APIKEY_PRIVATE}
            MJ_SENDER_EMAIL: ${MJ_SENDER_EMAIL}
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            SESSION_SECRET: ${SESSION_SECRET}
        ports:
            - 3001:3001
        env_file:
            - .env
